Update Troubleshooting Docs
karlvr/homebridge-roomba2 pull request #71
Opened 2021-09-22 20:29 UTC by rcoletti116

Instructions for finding IP address in iRobot app.

2021-09-22 22:26 UTC, karlvr requested changes

2021-09-22 22:26 UTC, karlvr commented on README.md
> +  >You can find your Roomba's IP Address in the iRobot app. Open the app and choose your Robot. Scroll down to the botom and find Robot Settings. Click Wi-Fi Settings and then Robot Wi-FI Details. Yo
This paragraph is in here twice.

2021-09-22 22:26 UTC, karlvr commented on README.md
> +  >You can find your Roomba's IP Address in the iRobot app. Open the app and choose your Robot. Scroll down to the botom and find Robot Settings. Click Wi-Fi Settings and then Robot Wi-FI Details. Yo
Bottom is misspelled

2021-09-22 22:26 UTC, karlvr commented on README.md
> -  >In order to find your Roomba's IP address, you'll need to open up your Router Admin Panel and look for a list of devices. Once you identify the Roomba, you should see an associated IP address, how
I'm not sure we should remove the previous instructions. I think that can be an Alternatively… paragraph?

2021-09-22 22:26 UTC, karlvr commented on README.md
>    <summary>I don't know what my Roomba's IP address is</summary>
How about we change this to _Finding my Roomba's IP address_

2021-09-23 10:00 UTC, karlvr requested changes

2021-09-23 11:03 UTC, rcoletti116 commented on README.md
> +  <summary>Finding my Roomba's IP sddress</summary>
Ugh, sorry! I'll fix it shortly.

2021-09-23 22:27 UTC, karlvr commented on config.schema.json
> +             "noDockOnStop": {
I don't think this change is supposed to be in this PR!

2021-09-23 22:28 UTC, karlvr requested changes
Just that one glitch with the unexpected change.

2021-09-23 23:47 UTC, karlvr approved these changes

2021-09-23 23:47 UTC, merged

2021-09-23 23:48 UTC, karlvr commented
@rcoletti116 thank you!